# Generated by Django 6.1 on 2026-09-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommunityComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_id', models.IntegerField()),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('display_name', models.CharField(blank=True, max_length=150, null=True)),
                ('comment_text', models.TextField()),
                ('commented_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'community_comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, null=True)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('attachment', models.CharField(blank=True, max_length=500, null=True)),
                ('attachment_type', models.CharField(blank=True, max_length=10, null=True)),
                ('posted_by', models.IntegerField(blank=True, null=True)),
                ('display_name', models.CharField(blank=True, max_length=150, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='active', max_length=20, null=True)),
            ],
            options={
                'db_table': 'community_posts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('attachment', models.CharField(blank=True, max_length=500, null=True)),
                ('attachment_type', models.CharField(blank=True, max_length=10, null=True)),
                ('posted_by', models.IntegerField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='active', max_length=20, null=True)),
                ('priority', models.CharField(blank=True, default='normal', max_length=20, null=True)),
                ('audience', models.CharField(blank=True, default='Everyone', max_length=255, null=True)),
            ],
            options={
                'db_table': 'notices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NoticeSubmission',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('attachment', models.CharField(blank=True, max_length=500, null=True)),
                ('attachment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('submitted_by', models.CharField(blank=True, max_length=150, null=True)),
                ('submitter_type', models.CharField(blank=True, default='student', max_length=20, null=True)),
                ('status', models.CharField(blank=True, default='pending', max_length=20, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notice_submissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('teacher', 'Teacher'), ('club', 'Club')], default='student', max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
